In [1]:
Necessite d'installer graphviz : 
 - pip install graphviz
 - conda install graphviz

SyntaxError: invalid syntax (<ipython-input-1-69204eb95b45>, line 1)

In [4]:
from IPython.display import display, HTML
display(HTML("""
<style>
.output {
    display: flex;
    align-items: center;
    text-align: center;
}

.output_text pre {
  white-space: pre;
  font-size: 20px;
  text-align: center;
  line-height: 150%;
}

.rise-enabled .output_text pre {
  font-size: 35px;
}

</style>
"""))



# Arbres de décisions
![iris_tree](tree-307232_640.png) 

## Classification

In [3]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from os import system
import numpy as np

ModuleNotFoundError: No module named 'sklearn'

In [2]:
iris=load_iris()

In [3]:
X = iris.data[:, 2:] # les deux dernieres valeurs de chaque ligne ( longueur et largueur du pétale )

In [4]:
X

array([[1.4, 0.2],
       [1.4, 0.2],
       [1.3, 0.2],
       [1.5, 0.2],
       [1.4, 0.2],
       [1.7, 0.4],
       [1.4, 0.3],
       [1.5, 0.2],
       [1.4, 0.2],
       [1.5, 0.1],
       [1.5, 0.2],
       [1.6, 0.2],
       [1.4, 0.1],
       [1.1, 0.1],
       [1.2, 0.2],
       [1.5, 0.4],
       [1.3, 0.4],
       [1.4, 0.3],
       [1.7, 0.3],
       [1.5, 0.3],
       [1.7, 0.2],
       [1.5, 0.4],
       [1. , 0.2],
       [1.7, 0.5],
       [1.9, 0.2],
       [1.6, 0.2],
       [1.6, 0.4],
       [1.5, 0.2],
       [1.4, 0.2],
       [1.6, 0.2],
       [1.6, 0.2],
       [1.5, 0.4],
       [1.5, 0.1],
       [1.4, 0.2],
       [1.5, 0.2],
       [1.2, 0.2],
       [1.3, 0.2],
       [1.4, 0.1],
       [1.3, 0.2],
       [1.5, 0.2],
       [1.3, 0.3],
       [1.3, 0.3],
       [1.3, 0.2],
       [1.6, 0.6],
       [1.9, 0.4],
       [1.4, 0.3],
       [1.6, 0.2],
       [1.4, 0.2],
       [1.5, 0.2],
       [1.4, 0.2],
       [4.7, 1.4],
       [4.5, 1.5],
       [4.9,

In [5]:
X.shape

(150, 2)

In [6]:
y = iris.target

In [7]:
tree = DecisionTreeClassifier(max_depth=2) # profondeur 2 
tree.fit(X, y)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=2,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [8]:
from sklearn.tree import export_graphviz

In [9]:
dotfile = open('iris_tree.dot', 'w')
export_graphviz(
    tree,
    out_file=dotfile,
    feature_names=iris.feature_names[2:],
    class_names=iris.target_names,
    rounded=True,
    filled=True    
)
dotfile.close()
system('dot -Tpng iris_tree.dot -o iris_tree.png')

0

![iris_tree](iris_tree.png)

In [10]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

### Explications

* Noeud Racine : est ce que la longueur du pétale est inférieure à 2.45cm , OUI / NON
* Si OUI , on arrive à un noeud Terminal sans aucune question , prédiction = setosa
* Si NON , est ce que la largeur du pétale est inférieure à 1.75cm etc...

### Attribut Samples 
l'attribut samples d'un noeud compte le nombre d'observations d'entrainement passées par ce noeud , par exemple 100 observations sont passés par le noeud de profondeur 1 à droite ( 100 fleurs ont une longueur de pétale supérieur à 2.45cm ) 
![Samples](samples.png)

### Attribut Values 
l'attribut values d'un noeud indique combien d'observations d'entrainement de chaque classe sont passées par la , par exemple le noeud de profondeur 2 à droite à été atteind par 0 setosa , 1 versicolor , 45 virginica 
![Value](value.png)

### Attribut Gini
l'attribut gini d'un noeud mesure son impureté , un noeud est pur ( gini = 0 ) si toutes les observations d'entrainement qui y aboutissent appartiennent à la meme classe
Exemple : 
pour le noeud de gauche de profondeur 1
![Gini](gini2.png)

$1 - (\frac{0}{54})^2 - (\frac{49}{54})^2 - (\frac{5}{54})^2 \approx 0.168$ 

Formule : $G_i = 1 - \Sigma_{k=1}^{n}p_{i,k}^2$

$p_{i,k}$ est le pourcentage d'observations de la classse k parmis toutes les toutes les observatons d'entrainement dans le ième noeud

Si un noeud est "pur" , c'est un noeud terminal qui ne peut plus etre partagé , la zone de droite est "impure" mais on a spécifié au début max_depth=2 , l'arbre de décision s'arrete donc la.

### Estimations des probabilités de classe
Un arbre de décision peut aussi estimer la probabilité qu'une observation appartienne à une classe donnée k , Supposons par exemple que vous ayez trouvé une fleur dont les pétales mesurent 5 cm de long et 1.5cm de large

In [11]:
tree.predict_proba([[5, 1.5]]) # 5cm de longueur , 1.5cm de largueur 

array([[0.        , 0.90740741, 0.09259259]])

L'arbre de décision renvoie les probabilités suivantes ( correspondant au noeud de profondeur 2 à gauche )  : 
- $ (\frac{0}{54}) =  0 \% $ pour setosa
- $ (\frac{49}{54}) =  90,7 \% $ pour versicolor
- $ (\frac{5}{54}) =  9,3 \% $ pour virginica

Si on demande à l'arbre de décision de prédire une classe il prédira donc Iris Versicolor ( classe 1 )  puisque c'est la classe avec la plus forte probabilité

In [12]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [13]:
tree.predict([[5, 1.5]]) # 5cm de longueur , 1.5cm de largueur

array([1])

### Algorithme d'entrainement CART ( Classification and Regression Tree ) 

- Scikit-Learn utilise l'algorithme CART pour entrainer les arbres de décisions 

Fonctionnement : 
- L'algorithme sépare d'abord le jeu d'entrainement en deux sous-ensembles en utilisant une seule caractéristique $k$ et un seuil $t_k$ ( ex : longueur de pétale <= 2.45cm ) 
- Cette paire $(k,t_k)$ est choisie en fonction de la paire qui produit les sous-ensembles les plus purs ( pondérés par leur taille )
- La fonction de cout que l'algorithme essaie de mnimiser est la suivante :

$J(k,t_k) = \frac{Mgauche}{m} * Ggauche + \frac{Mdroite}{m} * Gdroite $
 


$J(k,t_k) = \frac{Mgauche}{m} * Ggauche + \frac{Mdroite}{m} * Gdroite $

avec : 
- $ Ggauche / droite $ mesure l'impureté de sous ensemble de gauche/ de droite 
- $ Mgauche / droite $ est le nombre d'observation du sous ensemble de gauche / de droite

- Une fois le jeu d'entrainement partagé en deux , l'algorithme CART applique la meme logique aux sous-ensembles afin de les partager et ainsi de suite récursivement. La récursion ne s'interrompt que lorsque la profondeur maximale ( max_depth ) est atteinte

### Hyperparamètres

hyperparamètres de DecisionTreeClassifier ( sklearn ) : 

- __max_depth__ : controle de la profondeur de l'arbre , la valeur par défault = " None " signifie qu'il n'y pas de limites , en réduisant max_depth on réduit le risque de surajustement
- __min_samples_split__ : nombres minimum d'observations que doit comporter un noeud avant qu'il puisse etre divisé
- __min_samples_leaf__ : nombres minimums d'observation qu'un noeud terminal doit avoir
- __min_weight_fraction_leaf__ : identique à min_samples_leaf mais exprimé sous forme d'une fraction du nombre total d'observations pondérées
- __max_leaf_nodes__ : nombre maximum de noeuds terminaux
- __max_features__ : nombres maximum de caractéristiques évaluées à chaque noeud en vue de sa division
                       


                                       
- __criterion__ : gini ou entropy , par défaut gini , mesure de l'impureté d'un noeud 
- __splitter__ : best ou random , par defaut best , la strategie utilisé pour choisir le split à chaque noeud , best pour choisir le meilleur split , ou random pour choisir le meilleur split random
- __random_state__ : définition de la seed
- __max_impurity_decrease__ : float par défault 0.0 , le noeud sera fractionné si le fractionnement induit une diminution de l'impureté supérieure ou égale à cette valeur
- __min_impurity_split__ :  Seuil pour l'arret de croissance de l'arbre , un noeud se divise si son impureté est supérieure au seuil , sinon c'est un noeud terminal

### Instabilité

Les arbres de décison sont trés sensibles à de petites variations des données d'entrainement , les forets aléatoires peuvent limiter cette instabilité en effectuant une moyenne des prédictions sur de nombreux arbres

## avantages
* Modèle white box : Ils sont simples à comprendre et à visualiser.
* Ils nécessitent peu de préparation des données (normalisation, etc.).
* Le coût d’utilisation des arbres est logarithmique.
* Ils sont capables d’utiliser des données catégorielles et numériques.
* Ils sont capables de traiter des problèmes multi-classe.
![Avantages](avantages.png)


## Désavantages

* Overfitting Les arbres de décision peuvent créer des arbres trop complexes qui ne généralisent pas bien les données
* Les arbres de décision peuvent être instables car de petites variations dans les données peuvent entraîner la génération d'un arbre complètement différent. C'est ce qu'on appelle la variance, qui doit être réduite par des méthodes telles que le bagging et le boosting.
* L’apprentissage par arbre de décision crée des arbres biaisés si certaines classes dominent. Il est donc recommandé d'équilibrer l'ensemble des données avant de l'adapter à l'arbre de décision 
![Desavantages](desavantages.png)


# Questions

![Questions](questions.jpg)

### Sources : 
- Machine Learning avec Scikit-Learn de Aurélien Géron

- [Wikistat : Arbres binaires de décision](https://www.math.univ-toulouse.fr/~besse/Wikistat/pdf/st-m-app-cart.pdf)